sudo: required
services:
- docker
language: python
python:
- '3.6'
before_install:
- docker version
- docker info
install:
- nvm install --lts
- npm install newman
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install nose
- pip install Flask-Testing
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- python -m unittest discover
- docker build -t swagger-spring-example:1.0.0 .
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 swagger-spring-example:1.0.0
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag devops-app/swagger_server devops-app/swagger_server
- docker push devops-app/swagger_server
env:
  global:
  - secure: feGrboTZZ7c0ZhaPehiUTC/5IeQ2LWTnEUoJyhjxLiEeyK6pJ28XjSps4h2KE2KAFylGs9RvbhIEEK2HTsbWohWR88Wql8PJgym6F3PKs5oT2ACdgSeNaPQaxqEcfok1xlYdzOiGx9fmsbytk6/fA7Xg5ygd935MuuGbi5w20qR7AYed7DOsra5TLhGA5l9lMUy59/mZdHqog3ADDLH09t/bgbqGPVwMEYdmidrarmkg3xBapTZD2ySK18/cYna044vRv5Ucg3dbGBcyqQWtLlk3ZW6Il1RaK6h+KuaCBPyR6QAa+HVK9ydTFUH8ZNYfK75ZvJo5lh79O8UcTa6pbGctt7Vpa4EuHm9J2Opgrfde8pawA3ZQ1ctu9rrHmJc0BWMedM1L490sEuN4G8LysNpzYQP5NKW4nAT1EKAe5pTJTi2b1Qx4lD8exv4t/VwxFD+78d7vVvtxsif+QB//2bR5AlTRnEOQh+7TX53z2AZ6Sl9suYL0SoAg/yqN592V4B4Juk2BA0zszodZ+HNylCqsGhkPn7/eY9MEgqksndFa48IqdRmkOE/1/0GGwhddS/BGgzuxHG7Da90j/bFhjzMHAXlVVSkqMnkKtdurCknYZmSgXjQhD/cPp97h9QcEIoxnD3/mtU5NcQ5d/mf4Vxry34ZsA01Ut2PFrCW3Ha0=
  - secure: oRvFzqdAB9S6IHZcf+4ryIi2NSiBt2ei5wsiIvZjUuBNOTaWV+jzTLhdpwivbBG0n+ADNKLs7jYyOEUadnlnML73Iz51VRLqVLnk+SPIOcG6jiQ++GHuWwZ9aEgTlBItnYOM7GiZIukCIdXcVm33bmNYD21Ts5jXaBDgRMwziytpefbk3aIW+iyAyQj99kPSAF3HcuItH7HKMR899LbttIO6YlV0G3m4uyYj0CtBmqXFp478YFM05uC6KtjUU8xPsN+2pRCDreagoEGEGNFTYML6hx1/Y6D9ykWnFHR/FoN7DwenC7V2ZyDNELFWRxsSfH5i61eSQf15xWeSZ8KVgReykdnzAQ3MJVD1kZ3cko81BL8p1xPtZD90gX/tESXW7VA+IpdqQDZoaV5bPenVd4KsCq3TAP3CCngOBOH753oOAAO7EQGHCenjoXBzI3R2CE/bmVg2qH5fxkHKNxU2w/tZ9bqkL1soIo3f3f2jl5QSZwOJo5uPB7TcjHdFdJTHqVeL9FqJSoUHtQWMoclvPGIo4ER4xIyFqyRSTXPgede7twUG4OjB9Wwpsl0ihsICzzTkgqqCsl/siaAqkURo78YLoBvnGOURFHsN7jQHi4gr2yeLlqAuSDNRVHrrv+Yzkfvydmpdz4rLPad/opy53pZU5ZNhipKcdA2t/Nu+zbE=
