sudo: required
services:
- docker
language: python
python:
- '3.6'
before_install:
- docker version
- docker info
install:
- nvm install --lts
- npm install newman
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install nose
- pip install Flask-Testing
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- python -m unittest discover
- docker build -t swagger-spring-example:1.0.0 .
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 swagger-spring-example:1.0.0
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag enlitowl/devops-app:travis enlitowl/devops-app:travis
- docker push enlitowl/devops-app:travis
env:
  global:
  - secure: PUSecOW3U1thyA0dQBcgzE3c1V2OIxRrPVR5Yu3QA+w7HnMVfqKgKGzmpFp5totBNNOLbFf0p2yWOXkuTGDWljRXU15HiXqXag03p5ZVjtwk/O+I8FFFG7PBVsTYzGlFyGvIIIxc2iXPSLCwqat/7DQ+sldj4Euwt2lvUBvwvpgXysNkbjGtT159Xy2hekhDUB/Pw8t8hiIeQY2uZOni/dF40vShZH9bk+lkRIqwkcteMLR5YkNr2+hPr6cK0WGn+b553KsNO80yxiQdIqzul3LN9CkIAIVO8tPewqs10Pha2oF/ZQEVy1gAzXJTOAKMq00udnNAW6LOek6vXSF/e1UtJLF6w9li1+zYB6qVWnI829rYpfysuC3lr1n8jlUXFnBXTfEjIHzmkkhkNVFpcpWaAfiq+JgyitRb7Vyym+1fAHbipMVFnRDqB+d3dsiy4amqxF0JS7btCp8SHJVys2CJAauWJkiiiLSJIlvZZpEnFIPzWAowIgGjxnrPaRcvMWyUs1ac9rs+GO77qcFTFISnh2Kx8PA48lrCptH2/dDIJQFftt1lXNVvQI9ZXJDPKilNzIjkLlf39962eaMj3JCXeVEgiVClAfIxvDBlZqJSasfMvrmGLSm+QUQoSZpAQheUYyKOp96HQh0A5wX+tjHY9bi+DqlBB9qnOQXgz64=
  - secure: kKRtPpKMEUwKLYOENsW3nwKHBPamRT4FlXjBmxlvPnm7xHXtdQqomCjKf3xjIRnxUDqCaWB1PXoKhlDyN1kaN4cNssVU3oH1ir3XrytgQrTgkaKIReoxxNZHlbnm91PNyfhly/DrD0RxEqjoKiFYPWFOfIdD+04dtZvGRWlOiUKiHmS4CiJNXqg9jhA4k1Txdx6w/1DnAKJT0ccx4j3rwc1jAP30vk+HnlaXSQWP6MfzOKGWp6UNGgucw7W+7/0xLNrnsXtKU7BTKF/RzQwzoD1AjKL0UluZps6hMUCeK5wvhSowV0hiWs9wNP4P11h4jlj05SiTxRnya2rxpmMYfOD1Jlm2vSPKY/y3pJajAw7sNhas95Olpu0Sbxn1peanGeY84NAX9rzKkspzi9ej77/QDltUg8J69+dzcySrtkOBywLEgb/vlHt3YjSs4HQBgi65nKgiWwvL1DNwan6bBmb0liYQsOcpGBDauflPIXIF26e/Xoz+INfZv6wbePMZp5oAs8EDoaqDfUvJKfJDA79L8e/Iqk9ZrQiDhF2qxjVI85BolloiUBXv9kmHxwkjzOUAcnZtDFGfg4m+3tUI/rpMTY0yVpw/89VtWGLfcr41oKc7Vy6fGVT1b+PyT8wV1YBxkUVXyJLt3qaRHH264qn19ebagxwl1WFz8/aZIS0=
